[project]
name = "system-retrieval-fundamentals"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nltk>=3.9.2",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
]
